name: CD - Release quangnguyen-api

on:
    push:

    pull_request:
        branches:
            - dev
            - staging
            - master
    workflow_dispatch:
jobs:
    setup-env:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '16.x'

            - name: Install cdk
              run: yarn install -g cdk

            - name: Install typescipt
              run: yarn global add typescript

            - name: Install dependency
              run: yarn install

    deploy-dev:
        runs-on: ubuntu-latest
        needs: setup-env
        if: success() && github.ref == 'refs/heads/dev'
        steps:
            - name: Deploy dev
              run: yarn run deploy-dev

    deploy-staging:
        runs-on: ubuntu-latest
        needs: setup-env
        if: success() && github.ref == 'refs/heads/staging'
        steps:
            - name: Deploy staging
              run: yarn run deploy-staging

    deploy-prod:
        runs-on: ubuntu-latest
        needs: setup-env
        if: success() && github.ref == 'refs/heads/master'
        steps:
            - name: Deploy prod
              run: yarn run deploy-prod
